list(
  mkEffectFn1 = function(fn)function(x)fn(x)(),
  mkEffectFn2 = function(fn)function(a, b)fn(a, b)(),
  mkEffectFn3 = function(fn)function(a, b, d)fn(a, b, d)(),
  mkEffectFn4 = function(fn)function(a, b, d, e)fn(a, b, d, e)(),
  mkEffectFn5 = function(fn)function(a, b, d, e, f)fn(a, b, d, e, f)(),
  mkEffectFn6 = function(fn)function(a, b, d, e, f, g)fn(a, b, d, e, f, g)(),
  mkEffectFn7 = function(fn)function(a, b, d, e, f, g, h)fn(a, b, d, e, f, g, h)(),
  mkEffectFn8 = function(fn)function(a, b, d, e, f, g, h, i)fn(a, b, d, e, f, g, h, i)(),
  mkEffectFn9 = function(fn)function(a, b, d, e, f, g, h, i, j)fn(a, b, d, e, f, g, h, i, j)(),
  mkEffectFn10 = function(fn)function(a, b, d, e, f, g, h, i, j, k)fn(a, b, d, e, f, g, h, i, j, k)(),
  runEffectFn1 = function(fn)function(a)function()fn(a),
  runEffectFn2 = function(fn)function(a)function(b)function()fn(a, b),
  runEffectFn3 = function(fn)function(a)function(b)function(d)function()fn(a, b, d),
  runEffectFn4 = function(fn)function(a)function(b)function(d)function(e)function()fn(a, b, d, e),
  runEffectFn5 = function(fn)function(a)function(b)function(d)function(e)function(f)function()fn(a, b, d, e, f),
  runEffectFn6 = function(fn)function(a)function(b)function(d)function(e)function(f)function(g)function()fn(a, b, d, e, f, g),
  runEffectFn7 = function(fn)function(a)function(b)function(d)function(e)function(f)function(g)function(h)function()fn(a, b, d, e, f, g, h),
  runEffectFn8 = function(fn)function(a)function(b)function(d)function(e)function(f)function(g)function(h)function(i)function()fn(a, b, d, e, f, g, h, i),
  runEffectFn9 = function(fn)function(a)function(b)function(d)function(e)function(f)function(g)function(h)function(i)function(j)function()fn(a, b, d, e, f, g, h, i, j),
  runEffectFn10 = function(fn)function(a)function(b)function(d)function(e)function(f)function(g)function(h)function(i)function(j)function(k)function()fn(a, b, d, e, f, g, h, i, j, k),
)
